apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: nks-aiautomatisering
  name: nais-fastapi-template
  namespace: nks-aiautomatisering
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  ingresses:
    - https://nais-fastapi-template.ansatt.nav.no/
  liveness:
    path: /is_alive
    initialDelay: 20
    periodSeconds: 6
    timeout: 2
  readiness:
    path: /is_ready
    initialDelay: 20
    periodSeconds: 6
    timeout: 10
